### ISSUE TITLE
Disable email notifications from Bitbucket tests

### ISSUE THREAD

**Issue by dreis2211** [autobump/autobump#144]
Hi,

I'm getting frequent emails when you're testing your software on Bitbucket, because I'm basically mentioned in every release note of Spring-Boot.

Please find a way to stop those emails.

Cheers,
Christoph

**Comment by the-jos** [comment]
Hi Christoph,

We're so sorry for this! Should be fixed now.

#145 

Regards
Jos

**Comment by timpeeters** [comment]
Sorry, I understand this must be annoying.
I assume this happens because the release notes contain "at" dreis2211 and although this is a reference to your GitHub user, it probably triggers a notification because the user exists on BitBucket as well. We now remove the username mentions from the release notes.
