### ISSUE TITLE
Pull request includes release notes

### ISSUE THREAD

**Issue by timpeeters** [autobump/autobump#62]
User story:
As a developer,
I want Autobump to include release notes in the pull request description if they are available
in orde to save time when reviewing the pull request.

**Comment by the-jos** [comment]
Did a first investigation, flow looks like this:
1) download dependencies
2) parse SCM tags (scm/url/issueManagement) in build/project files for project url
3) querry appropriate git provider api under eg. /releases and search if it contains version nr
4) if so, fetch release notes body out of json

The first and second steps seem challenging because the project url can show up in several places, or none. Furthermore we'll need separate parsing logic per git provider (github/gitlab/bitbucket) and also per dependency type (maven, gradle, ...)

Interesting links:
- https://github.com/dependabot/dependabot-core/blob/master/maven/lib/dependabot/maven/metadata_finder.rb
- https://stackoverflow.com/questions/2910162/how-to-get-an-artifact-download-url-via-maven-api

**Comment by timpeeters** [comment]
I would like to limit the scope of the first implementation.

In the first implementation I would only support Maven dependencies with a value in the `<scm><url>` tag. And only if it contains a GitHub URL.

I would then check the GitHub releases endpoint to see if we can find release notes for the update we are proposing.

In the core, we could have interfaces like `ReleaseNotesSource` that abstracts the details and allows to add additional sources in the future next to GitHub.

E.g. Spring Boot parent pom:
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.3.0.RELEASE/spring-boot-dependencies-2.3.0.RELEASE.pom

Contains the following in scm/url:
https://github.com/spring-projects/spring-boot

From there we can deduct the release notes info for a specific release. E.g. the 2.3.0.RELEASE:
https://github.com/spring-projects/spring-boot/releases/tag/v2.3.0.RELEASE

Using the REST API of GitHub we can retrieve the release notes body:
https://api.github.com/repos/spring-projects/spring-boot/releases/tags/v2.3.0.RELEASE
(last element in the JSON)
